---
language: ruby
cache: bundler
bundler_args: --without development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script: 'bundle exec rake validate && bundle exec rake lint && bundle exec rake test SPEC_OPTS="--format documentation"'
env:
  - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.5" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.1"
  - PUPPET_VERSION="~> 4.7.0"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.5" FUTURE_PARSER=yes
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
